{'size': Size(width=10, height=10), 'tiles': [[Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0))], [
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0))],
                                              [Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0))], [
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0))],
                                              [Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=2, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=3, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=1, thystame=0, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=2, linemate=1, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=1, thystame=1, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0))], [
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=True,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=True,
                                                       objects=Resources(food=1, linemate=2, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=True,
                                                       objects=Resources(food=1, linemate=0, deraumere=1, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0))],
                                              [Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=2, linemate=1, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=1, thystame=1, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=1, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=True,
                                                    objects=Resources(food=0, linemate=1, deraumere=1, sibur=2,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0))], [
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0))],
                                              [Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0)),
                                               Tile(known=False,
                                                    objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                      mendiane=0, phiras=0, thystame=0, player=0))], [
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0)),
                                                  Tile(known=False,
                                                       objects=Resources(food=0, linemate=0, deraumere=0, sibur=0,
                                                                         mendiane=0, phiras=0, thystame=0, player=0))]]}
